[unstable]
build-std-features = ["compiler-builtins-mem"] # use rust memcpy etc implementation since no C implementation exists for us
build-std = ["core", "compiler_builtins"] # recompile core and compiler_builtins


[build]
target = "x86_64-r_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"